app:
  forecast_features_path: data/processed/forecast_features.parquet
  gru_model_path: artefacts/gru4rec.pt
  host: 0.0.0.0
  item2idx_path: artefacts/item2idx.json
  lightgbm_model_path: artefacts/lightgbm_weighted.pkl
  max_seq_length: 50
  port: 8000
  reco_sequences_path: data/processed/reco_sequences.parquet
clean:
  bot_threshold_per_day: 10000
  dedupe: true
  drop_missing_category: true
  out_dir: data/interim
  raw_dir: data/raw
features:
  forecast_horizon_days: 7
  freq: D
  in_dir: data/interim
  item2idx_path: artefacts/item2idx.json
  max_seq_length: 50
  min_interactions_per_user: 5
  out_dir: data/processed
  processed_forecast_path: forecast_features.parquet
  processed_reco_path: reco_sequences.parquet
  rolling_window_days: 30
models:
  artefacts_dir: artefacts
  features_dir: data/processed
  forecast:
    bagging_fraction: 0.7017410651716997
    bagging_freq: 3
    drop_zero_target: true
    early_stopping_rounds: 30
    feature_fraction: 0.9807646323675764
    lambda_l1: 1.3317603478605546
    lambda_l2: 0.020647496888965056
    learning_rate: 0.1453407588647221
    metric: mae
    min_data_in_leaf: 68
    num_boost_round: 300
    num_leaves: 16
    objective: regression
    optuna_db_path: artefacts/optuna_forecast.db
    optuna_pruner: median
    optuna_timeout_minutes: 20
    optuna_trials: 25
    tuned_model_weighted_path: artefacts/lightgbm_tuned_weighted.pkl
    use_sample_weight: true
    weighted_model_path: artefacts/lightgbm_weighted.pkl
  optuna_trials: 25
  reco:
    batch_size: 128
    embedding_dim: 32
    epochs: 5
    hidden_size: 64
    learning_rate: 0.001
    tuned_metrics_path: reports/metrics_reco_tuned.yaml
    tuned_model_path: artefacts/gru4rec.pt
  val_split_days: 7
report:
  notebook_path: notebooks/99_report.ipynb
  pdf_path: reports/report.pdf
